# Lyrics from songs from The Secret Path album by Gord Downie
# sourced from Spotify

lyrics <- 
  c( 
    # The Stranger
    "I am a stranger, you can't see me",
    "I am a stranger, do you know what I mean?",
    "I navigate the mud, I walk above the path",
    "Jumpin' to the right, then I jump to the left",
    "On a secret path, the one that nobody knows",
    "And I'm moving fast on the path that nobody knows",
    "And what I'm feelin' is anyone's guess",
    "What is in my head and what's in my chest",
    "I'm not gonna stop, I'm just catching my breath",
    "They're not gonna stop",
    "Please just let me catch my breath",
    "I am the stranger, you can't see me",
    "I am the stranger, do you know what I mean?",
    "That is not my dad, my dad is not a wild man",
    "Doesn't even drink - My dad, he's not a wild man",
    "On a secret path, the one that nobody knows", 
    "And I'm moving fast - On the path that nobody knows",
    "I am a stranger",
    "I am a stranger - I am a stranger - I am a stranger",
    
    # Swing set
    'We were at the swing set',
    '"Now?" I asked, "Not yet," you said',
    'Turn around in my seat - Chains chiming over my head',
    'When the tension is complete - And there is no way out of it',
    '"Now?", "Not yet" - "Now?", "Not yet"',
    'Over the rise on the law - Someone dragging someone',
    'The kid looking me in the eye - Teacher not looking at anyone',
    '"Now?", "Now, yes" - "Now?", "Now, yes"',
    "I looked behind me only once - Didn't see nobody chasin' us",
    'But just my swing dancing in the sun',
    'Dancing wildly where it was - "Now?", "Now, yes"',
    '"Now?", "Now, yes" - "Now, yes" - "Now, yes" - "Now, yes" - "Now, yes"',
    
    # I will not be struck
    "In this earth-like world, In this earth-like world",
    "Before they arrived under this sun-like star",
    "Under the sun-like star, they civilized",
    "Run along the river on the Secret Path",
    "I will not be struck, I'm not going back",
    "I can see my father's face, warming his feet by the stove",
    "We used to have each other, now we only have ourselves", 
    "Then I put my ear, then I put my ear",
    "Right against the rail, so what I couldn't hear",
    "What I couldn't hear, I would feel",
    "Run along the river on the Secret Path",
    "I will not be struck, I'm not going back",
    "I been staring into space, forever or else",
    "Enter the wilderness and we only have ourselves",
    
    # Son
    "You know that they just can't resist",
    "No man could make them feel nervous",
    "And they put zero into it - And their country doesn't exist",
    "Son, when you dance - I'll be on your shoulder, and you'll feel it",
    "Son, when you dance - I'll be on your shoulder, and you'll feel it",
    "And when something stirs in your heart",
    "A feeling so strong and intense",
    "When something occurs in your heart",
    "And there isn't a next sentence",
    "Son, when you dance - I'll be on your shoulder, and you'll feel it",
    "Even as the world convulses",
    "Don't stop wishing what you wish",
    "Even as the world convulses - Even as the world convulses",
    "Don't stop wishing the things you wish",
    "Don't stop wishing what you wish",
    "And when something stirs in your heart",
    "A feeling so strong and intense",
    "When something occurs in your heart",
    "And there isn't a next sentence")